# ------ Samples ------
samples: '*' # specify a list samples to use or '*' to use all samples
data:  /home/student/datasets/infant_gut  # path to data folder

# ------ Resources ------
threads : 8 # single task nb threads

# ----- Annotation database -----
cog_database: /home/student/databases/rpsblast_cog_db # COG database

# ----- Binning parameters ------
concoct:
    contig_size: 1000

# ------ Assembly parameters ------ 
read_length: 100
assembly:
    assembler: spades
    k: [55]
    mem: 14
    threads: 24

# ----- BayesPaths parameters ------
bayespaths:
    nb_strains: 5
    nmf_runs: 1
    max_giter: 1
    min_orf_number_to_merge_bins: 10
    min_orf_number_to_run_a_bin: 10
    percent_unitigs_shared: 0.1

# ----- DESMAN parameters ------
desman:
    execution: 1
    nb_haplotypes: 10
    nb_repeat: 5
    min_cov: 1
